package:适配mt76x8写mac功能

diff --git a/package/base-files/files/sbin/setmac b/package/base-files/files/sbin/setmac
--- a/package/base-files/files/sbin/setmac
+++ b/package/base-files/files/sbin/setmac
@@ -1,19 +1,19 @@
 #!/bin/sh
 . /lib/functions/caldata.sh
 if [ -e "/dev/mtd0" ]; then
-part="$(find_mtd_part Factory)"
+part="$(find_mtd_part factory)"
 elif [ -e "/dev/mmcblk0" ]; then
 part="$(find_mmc_part factory)"
 fi
-[ -n "$part" ] || { echo "Partition 'Factory' not found!"; exit 1; }
+[ -n "$part" ] || { echo "Partition 'factory' not found!"; exit 1; }
 mac="$1"
 validate_data macaddr "$mac" >"/dev/null" 2>&1 || { echo "Please specify a correct MAC address!"; exit 1; }
-dd if="$part" of="/tmp/Factory.backup" 2>"/dev/null"
-caldata_patch_mac "$mac" "0x4" "" "/tmp/Factory.backup" 2>"/dev/null"
+dd if="$part" of="/tmp/factory.backup" 2>"/dev/null"
+caldata_patch_mac "$mac" "0x4" "" "/tmp/factory.backup" 2>"/dev/null"
 if [ -e "/dev/mtd0" ]; then
-mtd -qq write "/tmp/Factory.backup" "Factory"
+mtd -qq write "/tmp/factory.backup" "factory"
 else
-dd if="/tmp/Factory.backup" of="$part" bs=512 conv=fsync 2>"/dev/null"
+dd if="/tmp/factory.backup" of="$part" bs=512 conv=fsync 2>"/dev/null"
 fi
-rm -rf "/tmp/Factory.backup"
-rm -rf "/overlay/upper/lib/firmware"/MT798*_PALNA_EEPROM.bin
+rm -rf "/tmp/factory.backup"
+rm -rf "/overlay/upper/lib/firmware"/MT762*_PALNA_EEPROM.bin
